require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 100

Performance/MapMethodChain:
  Enabled: true
